name: "Publish Release vule-magics-python2"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        default: "0.1.0"
        required: true

jobs:
  build_and_publish_stable:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vule_magics_python2
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 2

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools wheel requests

      - name: Update __VERSION__
        run: python ./scripts/update_version.py --version ${{ github.event.inputs.version }}

      - name: Build stable distribution
        run: |
          rm -rf dist/*
          python setup.py sdist bdist_wheel
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}