name: "Publish Release vule-magics-python2"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        default: "0.1.0"
        required: true

jobs:
  publish_release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vule_magics_python2
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 2

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools twine build

      - name: Update __VERSION__
        run: python ./scripts/update_version.py --version ${{ github.event.inputs.version }}

      - name: Publish the Python package
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m build
          twine upload dist/*